title: Ing. Artem Kandaurov # name of the site
author: Artem Kandaurov # name of site's author
email: artem@kandaurov.net # email of site's author
url: http://www.kandaurov.net # root address of the site
baseurl: "" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: "<b>Senior Software Developer / Quantum Computing Researcher</b> <br> <br> Bachelor's and Master's degrees in Computer Science. More than 10 years of development experience. Deep knowledge of iOS / iPadOS / watchOS / tvOS / macOS platforms. Engaged and experienced tech lead. Quantum computing enthusiast. <br> <br>"

permalink: /:slug.html

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
goat_counter: "kandaurovnet" # put your GoatCounter name if you want to use GoatCounter analytics

remote_theme: riggraz/no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%d/%m/%Y" # customize how date is formatted
  show_description: true # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
